package com.rwi.myrepublic.astri.internal;import com.rwi.myrepublic.astri.AstriConfig;import java.io.*;import java.net.URI;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.Paths;import java.time.Duration;import java.util.Base64;import java.util.UUID;import java.util.zip.ZipEntry;import java.util.zip.ZipOutputStream;public class DocumentUploadClient{private final HttpClient
client;private final AstriConfig config;private final String authHeader;public DocumentUploadClient(){this.config=AstriConfig.getInstance();this.client=HttpClient.newBuilder().connectTimeout(Duration.ofMillis(config.getConnectionTimeout())).build();String credentials=config.getUsername()+ ":"+config.getPassword();this.authHeader= "Basic "+Base64.getEncoder().encodeToString(credentials.getBytes());}public String uploadDocument(String filePath,String typeName,String clusterCode,String
ospRouteName,String oltName,String oltSiteName)throws IOException,InterruptedException{Path inputPath=Paths.get(filePath);if(!Files.exists(inputPath)){return buildErrorXml("File not found: "+filePath,0);}Path kmzPath=ensureKmz(inputPath);byte[]fileBytes=Files.readAllBytes(kmzPath);String actualFileName=kmzPath.getFileName().toString();String boundary= "----AstriBoundary"+UUID.randomUUID().toString().replace("-", "");ByteArrayOutputStream bodyOut=new
ByteArrayOutputStream();writeFileField(bodyOut,boundary, "file",actualFileName,fileBytes);writeTextField(bodyOut,boundary, "type_name",typeName);writeTextField(bodyOut,boundary, "filename",actualFileName);if(isPresent(clusterCode))writeTextField(bodyOut,boundary, "cluster_code",clusterCode);if(isPresent(ospRouteName))writeTextField(bodyOut,boundary, "osp_route_name",ospRouteName);if(isPresent(oltName))writeTextField(bodyOut,boundary,
"olt_name",oltName);if(isPresent(oltSiteName))writeTextField(bodyOut,boundary, "olt_site_name",oltSiteName);String closingBoundary= "--"+boundary+ "--\r\n";bodyOut.write(closingBoundary.getBytes("UTF-8"));byte[]bodyBytes=bodyOut.toByteArray();String url=config.getDmBaseUrl()+ "/osp/cluster/document/add/multipart";HttpRequest request=HttpRequest.newBuilder().uri(URI.create(url)).header("Authorization",authHeader).header("Content-Type",
"multipart/form-data; boundary="+boundary).timeout(Duration.ofMillis(config.getRequestTimeout())).POST(HttpRequest.BodyPublishers.ofByteArray(bodyBytes)).build();HttpResponse<String>response=client.send(request,HttpResponse.BodyHandlers.ofString());int statusCode=response.statusCode();String body=response.body();if(statusCode>=200&&statusCode<300){return buildSuccessXml(body,statusCode);}else{return buildErrorXml("HTTP "+statusCode+ ": "+body,statusCode);}}private Path ensureKmz(Path
inputPath)throws IOException{String name=inputPath.getFileName().toString();if(name.toLowerCase().endsWith(".kml")){String baseName=name.substring(0,name.length()-4);Path kmzPath=inputPath.resolveSibling(baseName+ ".kmz");try(ZipOutputStream zos=new ZipOutputStream(Files.newOutputStream(kmzPath))){zos.putNextEntry(new ZipEntry(name));zos.write(Files.readAllBytes(inputPath));zos.closeEntry();}return kmzPath;}return inputPath;}private void writeTextField(OutputStream out,String boundary,String
fieldName,String value)throws IOException{String part= "--"+boundary+ "\r\n"+ "Content-Disposition: form-data; name=\""+fieldName+ "\"\r\n"+ "\r\n"+value+ "\r\n";out.write(part.getBytes("UTF-8"));}private void writeFileField(OutputStream out,String boundary,String fieldName,String fileName,byte[]fileBytes)throws IOException{String header= "--"+boundary+ "\r\n"+ "Content-Disposition: form-data; name=\""+fieldName+ "\"; filename=\""+fileName+ "\"\r\n"+
"Content-Type: application/vnd.google-earth.kmz\r\n"+ "\r\n";out.write(header.getBytes("UTF-8"));out.write(fileBytes);out.write("\r\n".getBytes("UTF-8"));}private String buildSuccessXml(String rawBody,int httpStatus){StringBuilder xml=new
StringBuilder();xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");xml.append("<response>\n");xml.append("  <success>true</success>\n");xml.append("  <http_status>").append(httpStatus).append("</http_status>\n");xml.append("  <message><![CDATA[").append(rawBody).append("]]></message>\n");xml.append("</response>");return xml.toString();}private String buildErrorXml(String errorMsg,int httpStatus){StringBuilder xml=new
StringBuilder();xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");xml.append("<response>\n");xml.append("  <success>false</success>\n");xml.append("  <http_status>").append(httpStatus).append("</http_status>\n");xml.append("  <error>").append(escapeXml(errorMsg)).append("</error>\n");xml.append("</response>");return xml.toString();}private String escapeXml(String str){if(str==null)return "";return str.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"",
"&quot;").replace("'", "&apos;");}private boolean isPresent(String value){return value!=null&&!value.trim().isEmpty();}public void close(){}}