package com.rwi.myrepublic.astri.internal;import com.rwi.myrepublic.astri.AstriConfig;import java.io.*;import java.net.URI;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.nio.file.Files;import java.nio.file.Path;import java.nio.file.Paths;import java.time.Duration;import java.util.Base64;import java.util.zip.ZipEntry;import java.util.zip.ZipInputStream;public class KmzDownloadClient{private HttpClient client;private AstriConfig
config;private String authHeader;public KmzDownloadClient(){this.config=AstriConfig.getInstance();this.client=HttpClient.newBuilder().connectTimeout(Duration.ofMillis(config.getConnectionTimeout())).build();String credentials=config.getUsername()+ ":"+config.getPassword();this.authHeader= "Basic "+Base64.getEncoder().encodeToString(credentials.getBytes());}public String downloadClusterDocument(String uuid,String outputDir)throws IOException,InterruptedException{return
downloadDocument("cluster",uuid,outputDir);}public String downloadSubfeederDocument(String uuid,String outputDir)throws IOException,InterruptedException{return downloadDocument("subfeeder",uuid,outputDir);}public String downloadFeederDocument(String uuid,String outputDir)throws IOException,InterruptedException{return downloadDocument("feeder",uuid,outputDir);}public String downloadOltSiteDocument(String uuid,String outputDir)throws IOException,InterruptedException{return
downloadDocument("olt-site",uuid,outputDir);}private String downloadDocument(String docType,String uuid,String outputDir)throws IOException,InterruptedException{String baseUrl=config.getDmBaseUrl();String path;switch(docType){case "cluster":path= "/osp/cluster/document/cluster/download/"+uuid;break;case "subfeeder":path= "/osp/cluster/document/subfeeder/download/"+uuid;break;case "feeder":path= "/osp/cluster/document/feeder/download/"+uuid;break;case "olt-site":path=
"/osp/cluster/document/olt/site/download/"+uuid;break;default:throw new IllegalArgumentException("Unknown document type: "+docType);}HttpRequest request=HttpRequest.newBuilder().uri(URI.create(baseUrl+path)).header("Authorization",authHeader).timeout(Duration.ofMillis(config.getRequestTimeout())).GET().build();HttpResponse<byte[]>response=client.send(request,HttpResponse.BodyHandlers.ofByteArray());byte[]kmzData=response.body();String kmlContent= "";try(ZipInputStream zis=new ZipInputStream(new
ByteArrayInputStream(kmzData))){ZipEntry entry;while((entry=zis.getNextEntry())!=null){if(entry.getName().toLowerCase().endsWith(".kml")){ByteArrayOutputStream baos=new ByteArrayOutputStream();byte[]buffer=new byte[1024];int len;while((len=zis.read(buffer))>0){baos.write(buffer,0,len);}kmlContent=baos.toString("UTF-8");break;}zis.closeEntry();}}if(outputDir==null||outputDir.trim().isEmpty()){StringBuilder xml=new
StringBuilder();xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");xml.append("<response>\n");xml.append("  <success>true</success>\n");xml.append("  <document_type>").append(escapeXml(docType)).append("</document_type>\n");xml.append("  <uuid>").append(escapeXml(uuid)).append("</uuid>\n");xml.append("  <kml_content><![CDATA[").append(kmlContent).append("]]></kml_content>\n");xml.append("</response>");return xml.toString();}Path
dirPath=Paths.get(outputDir);if(!Files.exists(dirPath)){Files.createDirectories(dirPath);}String kmzFileName=docType+ "_"+uuid+ ".kmz";Path kmzFilePath=dirPath.resolve(kmzFileName);Files.write(kmzFilePath,kmzData);String kmlFileName=docType+ "_"+uuid+ ".kml";Path kmlFilePath=dirPath.resolve(kmlFileName);Files.write(kmlFilePath,kmlContent.getBytes("UTF-8"));StringBuilder xml=new
StringBuilder();xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");xml.append("<response>\n");xml.append("  <success>true</success>\n");xml.append("  <document_type>").append(escapeXml(docType)).append("</document_type>\n");xml.append("  <uuid>").append(escapeXml(uuid)).append("</uuid>\n");xml.append("  <kmz_file_path>").append(escapeXml(kmzFilePath.toString())).append("</kmz_file_path>\n");xml.append("  <kml_file_path>").append(escapeXml(kmlFilePath.toString())).append("</kml_file_path>\n");xml.append("</response>");return
xml.toString();}private String escapeXml(String str){if(str==null)return "";return str.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&apos;");}public void close(){}}