package com.rwi.myrepublic.astri.internal;import com.rwi.myrepublic.astri.AstriConfig;import java.io.IOException;import java.net.URI;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.time.Duration;import java.util.Base64;import java.util.regex.Matcher;import java.util.regex.Pattern;public class WorkOrderClient{private HttpClient client;private AstriConfig config;private String authHeader;public
WorkOrderClient(){this.config=AstriConfig.getInstance();this.client=HttpClient.newBuilder().connectTimeout(Duration.ofMillis(config.getConnectionTimeout())).build();String credentials=config.getUsername()+ ":"+config.getPassword();this.authHeader= "Basic "+Base64.getEncoder().encodeToString(credentials.getBytes());}public String getWorkOrders(String infrastructureType,int limit,int offset,String filterParams)throws IOException,InterruptedException{String baseUrl=config.getApiBaseUrl();String
path= "/work-order/"+infrastructureType+ "/boq/simple/list/all/"+limit+ "/"+offset;String url=baseUrl+path;if(filterParams!=null&&!filterParams.isEmpty()){url+= "?"+filterParams;}HttpRequest request=HttpRequest.newBuilder().uri(URI.create(url)).header("Authorization",authHeader).timeout(Duration.ofMillis(config.getRequestTimeout())).GET().build();HttpResponse<String>response=client.send(request,HttpResponse.BodyHandlers.ofString());String jsonResponse=response.body();return
convertJsonToXml(jsonResponse,infrastructureType);}public String getWorkOrder(String uuid)throws IOException,InterruptedException{String baseUrl=config.getApiBaseUrl();String path= "/api/work-order/"+uuid;HttpRequest request=HttpRequest.newBuilder().uri(URI.create(baseUrl+path)).header("Authorization",authHeader).timeout(Duration.ofMillis(config.getRequestTimeout())).GET().build();HttpResponse<String>response=client.send(request,HttpResponse.BodyHandlers.ofString());String
jsonResponse=response.body();return convertJsonToXml(jsonResponse, "cluster");}private String convertJsonToXml(String json,String infrastructureType){try{StringBuilder xml=new StringBuilder();xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");xml.append("<response>\n");String success=extractJsonValue(json, "success");String count=extractJsonValue(json, "count");String countAll=extractJsonValue(json, "count_all");String error=extractJsonValue(json,
"error");if(success!=null&&!success.isEmpty()){xml.append("  <success>").append(escapeXml(success)).append("</success>\n");}if(count!=null&&!count.isEmpty()){xml.append("  <count>").append(escapeXml(count)).append("</count>\n");}if(countAll!=null&&!countAll.isEmpty()){xml.append("  <count_all>").append(escapeXml(countAll)).append("</count_all>\n");}if(error!=null&&!error.isEmpty()){xml.append("  <error>").append(escapeXml(error)).append("</error>\n");}String
dataArray=extractDataArray(json);if(dataArray!=null&&!dataArray.isEmpty()){xml.append("  <data>\n");String[]workOrders=splitJsonObjects(dataArray);for(String woJson:workOrders){if(woJson.trim().isEmpty())continue;xml.append("    <workorder>\n");appendXmlField(xml,woJson, "uuid",6);appendXmlField(xml,woJson, "number",6);appendXmlField(xml,woJson, "category_label",6);appendXmlField(xml,woJson, "category_name",6);appendXmlField(xml,woJson, "latest_status_name",6);appendXmlField(xml,woJson,
"assigned_vendor_label",6);appendXmlField(xml,woJson, "assigned_vendor_name",6);appendXmlField(xml,woJson, "assigned_vendor_sap_vendor_code",6);appendXmlField(xml,woJson, "assigned_subcont_vendor_name",6);appendXmlField(xml,woJson, "created_at",6);appendXmlField(xml,woJson, "updated_at",6);String targetPrefix;if("feeder".equals(infrastructureType)){targetPrefix= "target_osp_route";}else{targetPrefix= "target_"+infrastructureType;}appendXmlField(xml,woJson,targetPrefix+
"_code",6);appendXmlField(xml,woJson,targetPrefix+ "_name",6);if("cluster".equals(infrastructureType)){appendXmlField(xml,woJson,targetPrefix+ "_topology",6);appendXmlField(xml,woJson, "target_cluster_area",6);appendXmlField(xml,woJson, "target_cluster_area_plant_code",6);appendXmlField(xml,woJson, "target_cluster_olt_name",6);appendXmlField(xml,woJson, "target_cluster_olt_label",6);}else if("subfeeder".equals(infrastructureType)){appendXmlField(xml,woJson,
"target_subfeeder_area",6);appendXmlField(xml,woJson, "target_subfeeder_area_plant_code",6);appendXmlField(xml,woJson, "target_subfeeder_olt_name",6);appendXmlField(xml,woJson, "target_subfeeder_olt_label",6);}else if("feeder".equals(infrastructureType)){appendXmlField(xml,woJson, "target_osp_route_area",6);appendXmlField(xml,woJson, "target_osp_route_area_plant_code",6);appendXmlField(xml,woJson, "target_osp_route_asset_number",6);appendXmlField(xml,woJson,
"target_osp_route_olt_name",6);appendXmlField(xml,woJson, "target_osp_route_olt_label",6);}xml.append("    </workorder>\n");}xml.append("  </data>\n");}xml.append("</response>");return xml.toString();}catch(Exception e){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"+ "<response>\n"+ "  <success>false</success>\n"+ "  <error>"+escapeXml(e.getMessage())+ "</error>\n"+ "</response>";}}private String extractJsonValue(String json,String fieldName){Pattern
quotedPattern=Pattern.compile("\""+Pattern.quote(fieldName)+ "\"\\s*:\\s*\"([^\"\\\\]*(?:\\\\.[^\"\\\\]*)*)\"");Matcher quotedMatcher=quotedPattern.matcher(json);if(quotedMatcher.find()){return quotedMatcher.group(1).trim();}Pattern unquotedPattern=Pattern.compile("\""+Pattern.quote(fieldName)+ "\"\\s*:\\s*([^,}\\s]+)");Matcher unquotedMatcher=unquotedPattern.matcher(json);if(unquotedMatcher.find()){return unquotedMatcher.group(1).trim();}return null;}private String extractDataArray(String
json){int dataStart=json.indexOf("\"data\"");if(dataStart==-1)return null;int arrayStart=json.indexOf("[",dataStart);if(arrayStart==-1)return null;int level=0;int arrayEnd=-1;for(int i=arrayStart;i<json.length();i++){char c=json.charAt(i);if(c== '[')level++;else if(c== ']'){level--;if(level==0){arrayEnd=i;break;}}}if(arrayEnd==-1)return null;return json.substring(arrayStart+1,arrayEnd);}private String[]splitJsonObjects(String jsonArray){java.util.List<String>objects=new
java.util.ArrayList<>();int level=0;int start=-1;for(int i=0;i<jsonArray.length();i++){char c=jsonArray.charAt(i);if(c== '{'){if(level==0)start=i;level++;}else if(c== '}'){level--;if(level==0&&start!=-1){objects.add(jsonArray.substring(start+1,i));start=-1;}}}return objects.toArray(new String[0]);}private void appendXmlField(StringBuilder xml,String json,String fieldName,int indent){String value=extractJsonValue(json,fieldName);if(value!=null&&!value.isEmpty()){String spaces=
" ".repeat(indent);xml.append(spaces).append("<").append(fieldName).append(">").append(escapeXml(value)).append("</").append(fieldName).append(">\n");}}private String escapeXml(String str){if(str==null)return "";return str.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&apos;");}public void close(){}}