:export     :en_gb Ekspor
:target_dir	:en_gb	Direktori Tujuan
:export_for	:en_gb	Ekspor Desain Untuk
:design	:en_gb	Desain dan Survei
:homepass	:en_gb	Homepass
:title    :en_gb Ekpor Desain ke KML
:browse   :en_gb Pilih
:close    :en_gb Tutup
:file_does_not_exist :en_gb Berkas #1 tidak ditemukan
:file_cannot_be_created	:en_gb	Berkas #1 tidak dapat dibuat
:template_missing	:en_gb	Berkas Template tidak ditemukan
:sel_dir_title	:en_gb	Pilih Direktori Tujuan

:no_open_design	:en_gb	Harap buka desain untuk melakukan ekspor
:no_scheme_area	:en_gb	Area Desain belum ditentukan
:process_start	:en_gb	Memulai proses
:create_file	:en_gb	Membuat berkas keluaran
:populating_object	:en_gb	Mengolah obyek
:exporting_object	:en_gb	Memulai ekspor obyek
:sto	:en_gb	Mengekspor STO #1
:tower	:en_gb	Mengekspor Tower #1
:pole	:en_gb	Mengekspor Pole #1
:uub	:en_gb	Mengekspor UUB #1
:sheath_splice	:en_gb	Mengekspor FAT #1
:terminal_enclosure	:en_gb	Mengekspor FDT #1
:cable	:en_gb	Mengekspor cable #1
:ugroute	:en_gb	Mengekspor underground route #1
:aroute	:en_gb	Mengekspor Aerial route #1
:dpoint	:en_gb	Mengekspor demand point #1
:finish	:en_gb	Proses selesai. Telah diekspor ke #1
:write_failed	:en_gb	Berkas tidak dapat dibuat

:help_text	:en_gb Proses ekspor data di desain untuk ekspor data
dari desain menjadi berkas KML
