:process_start	:en_gb	Starting process
:create_file	:en_gb	Creating output file
:populating_object	en_gb	Populating object
:exporting_object	:en_gb	Start exporting object
:sto	:en_gb	Exporting OLT #1
:pole	:en_gb	Exporting Pole #1
:uub	:en_gb	Exporting UUB #1
:sheath_splice	:en_gb	Exporting ODP #1
:terminal_enclosure	:en_gb	Exporting ODC #1
:cable	:en_gb	Exporting cable #1
:finish	:en_gb	Process done
:write_failed	:en_gb	File cannot be created